name: update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: cachix/install-nix-action@v27
    - name: update
      run: |
        nix flake update
        cd locker
        yarn
        ./build.sh
        cd ../../
        nix run .#update
    - name: build
      run: |
        nix build .
    - uses: stefanzweifel/git-auto-commit-action@v5.0.1
